FROM node:15 as builder

WORKDIR /app

COPY /src/node/package*.json .

RUN npm install 


FROM node:15-alpine3.13

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY /src/node/index.js /app

EXPOSE 3000

ENTRYPOINT ["node", "index.js"]
